// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnsvgvbuqorhwhsnfbat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuc3ZndmJ1cW9yaHdoc25mYmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2OTI4NDIsImV4cCI6MjA1NjI2ODg0Mn0.99zvzwfmdL_aQ_ZTgxhMyuCQfZ5Ruv7QrXiYwjoRhKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);